version: '3.8'

services:
  funkhouse-app-db:
    restart: always
    container_name: funkhouse-app-db
    image: postgres:13.4-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: authusr
      POSTGRES_PASSWORD: auth123
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: funkhouse-app
      WAIT_FOR_DB: 'true'
    networks:
      - app-net

  funkhouse-app:
    restart: unless-stopped
    container_name: funkhouse-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - NODE_ENV=${ENV:-development}
      - APP_PORT=${APP_PORT:-3000}
    depends_on:
      - funkhouse-app-db
    ports:
      - '${HTTP_PORT:-80}:${APP_PORT:-3000}'
    networks:
      - app-net

  fh-nginx-pgadmin:
    image: laurentbel/nginx-basic-auth
    ports:
      - "6060:80"
    depends_on:
      - fh-pgadmin
    environment:
      - FORWARD_HOST=fh-pgadmin
      - FORWARD_PORT=80
      - BASIC_USERNAME=${DB_BASIC_AUTH_LOGIN}
      - BASIC_PASSWORD=${DB_BASIC_AUTH_PASSWORD}
    networks:
      - app-net

  fh-pgadmin:
    restart: unless-stopped
    container_name: fh-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SERVER_MODE: 'False' # True if we use PGADMIN_DEFAULT_EMAIL and PGADMIN_DEFAULT_PASSWORD
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'supersecret'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    networks:
      - app-net

networks:
  app-net:
    name: app-net

volumes:
  pg-data: #driver: local
